### ISSUE TITLE
Option to delay the display of new windows while typing

### ISSUE THREAD

**Issue by Code7R** [Code7R/icewm#6]
Usual situation: login, open terminal, start reading mails there. Push "Firefox" button and keep reading mail. Firefox is configured to restore previous session on startup.

While working in the terminal (scrolling or even typing important things) first FF window appears and STEALS focus. ARGH. You press Alt-Tab to get the focus back, continuing typing there. A few seconds later a second FF window appears and steals the focus again. FFFUUUUU....

Idea: have an option to delay the creation of the window, waiting at least N seconds after the last keyboard event before the windows appear. Maybe there should appear as minimized or hidden (etc.) and maximize/get focus/... after $USER stopped typing.

**Comment by gijsbers** [comment]
I have seen that some apps on startup keep sending [_NET_ACTIVE_WINDOW](https://specifications.freedesktop.org/wm-spec/latest/ar01s03.html)
 messages to the window manager until they get focus, which makes it impossible to start them minimized or hidden. We could, for example, add an `ignoreActivate` option to winoptions?
