### ISSUE TITLE
Feature request: change order of window icons in taskbar

### ISSUE THREAD

**Issue by Vrihub** [Code7R/icewm#9]
Feature request: allow the user to change the order of the window icons in the taskbar, e.g. by dragging them, as you can do with tabs in modern browsers.

**Comment by Code7R** [comment]
Using which mouse button? With some mod key?

**Comment by Vrihub** [comment]
My obvious idea was by clicking with the left button and dragging, just like you do with tabs in Firefox.

**Comment by Code7R** [comment]
This is now solved in Debian Experimental. Clicking and dragging, as you suggested.

**Comment by Vrihub** [comment]
Thank you very much! That's exactly what I intended!
I've been testing it and I couldn't find any problems so far. Moreover, I've noticed that manually re-ordering icons in the taskbar doesn't interfere with the order of icons in the Alt-Tab switching cycle, which stays the same (as I expected).
